version: '3'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=''
            - POSTGRES_PASSWORD=''
            - POSTGRES_DB=''
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        hostname: pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=natan@natanascimento.com
            - PGADMIN_DEFAULT_PASSWORD=''
        depends_on:
            - postgres
        ports:
            - "18080:80"
    dbeaver:
      image: "dbeaver/cloudbeaver:latest"
      hostname: dbeaver
      restart: "unless-stopped"
      ports:
        - 8978:8978